//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserClass", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int userIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private int ageField;
        
        private int weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        private int DietPlan_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int weight {
            get {
                return this.weightField;
            }
            set {
                if ((this.weightField.Equals(value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int DietPlan_Id {
            get {
                return this.DietPlan_IdField;
            }
            set {
                if ((this.DietPlan_IdField.Equals(value) != true)) {
                    this.DietPlan_IdField = value;
                    this.RaisePropertyChanged("DietPlan_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DietPlanClass", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DietPlanClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vegesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fruitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string meatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string drinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string milkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string veges {
            get {
                return this.vegesField;
            }
            set {
                if ((object.ReferenceEquals(this.vegesField, value) != true)) {
                    this.vegesField = value;
                    this.RaisePropertyChanged("veges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fruit {
            get {
                return this.fruitField;
            }
            set {
                if ((object.ReferenceEquals(this.fruitField, value) != true)) {
                    this.fruitField = value;
                    this.RaisePropertyChanged("fruit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string meat {
            get {
                return this.meatField;
            }
            set {
                if ((object.ReferenceEquals(this.meatField, value) != true)) {
                    this.meatField = value;
                    this.RaisePropertyChanged("meat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string drinks {
            get {
                return this.drinksField;
            }
            set {
                if ((object.ReferenceEquals(this.drinksField, value) != true)) {
                    this.drinksField = value;
                    this.RaisePropertyChanged("drinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string milk {
            get {
                return this.milkField;
            }
            set {
                if ((object.ReferenceEquals(this.milkField, value) != true)) {
                    this.milkField = value;
                    this.RaisePropertyChanged("milk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginFunc", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.LoginFuncResponse LoginFunc(WindowsFormsApp1.ServiceReference1.LoginFuncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.LoginFuncResponse> LoginFuncAsync(WindowsFormsApp1.ServiceReference1.LoginFuncRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.RegisterResponse Register(WindowsFormsApp1.ServiceReference1.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.RegisterResponse> RegisterAsync(WindowsFormsApp1.ServiceReference1.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewProfile", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.ViewProfileResponse ViewProfile(WindowsFormsApp1.ServiceReference1.ViewProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ViewProfileResponse> ViewProfileAsync(WindowsFormsApp1.ServiceReference1.ViewProfileRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewDietPlan", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.ViewDietPlanResponse ViewDietPlan(WindowsFormsApp1.ServiceReference1.ViewDietPlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewDietPlan", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ViewDietPlanResponse> ViewDietPlanAsync(WindowsFormsApp1.ServiceReference1.ViewDietPlanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginFuncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginFunc", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.LoginFuncRequestBody Body;
        
        public LoginFuncRequest() {
        }
        
        public LoginFuncRequest(WindowsFormsApp1.ServiceReference1.LoginFuncRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginFuncRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginFuncRequestBody() {
        }
        
        public LoginFuncRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginFuncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginFuncResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.LoginFuncResponseBody Body;
        
        public LoginFuncResponse() {
        }
        
        public LoginFuncResponse(WindowsFormsApp1.ServiceReference1.LoginFuncResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginFuncResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginFuncResult;
        
        public LoginFuncResponseBody() {
        }
        
        public LoginFuncResponseBody(bool LoginFuncResult) {
            this.LoginFuncResult = LoginFuncResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(WindowsFormsApp1.ServiceReference1.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int weight;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string name, int age, int weight, string gender, string email, string password) {
            this.name = name;
            this.age = age;
            this.weight = weight;
            this.gender = gender;
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(WindowsFormsApp1.ServiceReference1.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterResponseBody {
        
        public RegisterResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewProfile", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.ViewProfileRequestBody Body;
        
        public ViewProfileRequest() {
        }
        
        public ViewProfileRequest(WindowsFormsApp1.ServiceReference1.ViewProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public ViewProfileRequestBody() {
        }
        
        public ViewProfileRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.ViewProfileResponseBody Body;
        
        public ViewProfileResponse() {
        }
        
        public ViewProfileResponse(WindowsFormsApp1.ServiceReference1.ViewProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference1.UserClass ViewProfileResult;
        
        public ViewProfileResponseBody() {
        }
        
        public ViewProfileResponseBody(WindowsFormsApp1.ServiceReference1.UserClass ViewProfileResult) {
            this.ViewProfileResult = ViewProfileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewDietPlanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewDietPlan", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.ViewDietPlanRequestBody Body;
        
        public ViewDietPlanRequest() {
        }
        
        public ViewDietPlanRequest(WindowsFormsApp1.ServiceReference1.ViewDietPlanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewDietPlanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string type;
        
        public ViewDietPlanRequestBody() {
        }
        
        public ViewDietPlanRequestBody(string type) {
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewDietPlanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewDietPlanResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.ViewDietPlanResponseBody Body;
        
        public ViewDietPlanResponse() {
        }
        
        public ViewDietPlanResponse(WindowsFormsApp1.ServiceReference1.ViewDietPlanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewDietPlanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference1.DietPlanClass ViewDietPlanResult;
        
        public ViewDietPlanResponseBody() {
        }
        
        public ViewDietPlanResponseBody(WindowsFormsApp1.ServiceReference1.DietPlanClass ViewDietPlanResult) {
            this.ViewDietPlanResult = ViewDietPlanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.WebService1Soap>, WindowsFormsApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.LoginFuncResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.LoginFunc(WindowsFormsApp1.ServiceReference1.LoginFuncRequest request) {
            return base.Channel.LoginFunc(request);
        }
        
        public bool LoginFunc(string email, string password) {
            WindowsFormsApp1.ServiceReference1.LoginFuncRequest inValue = new WindowsFormsApp1.ServiceReference1.LoginFuncRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.LoginFuncRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            WindowsFormsApp1.ServiceReference1.LoginFuncResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).LoginFunc(inValue);
            return retVal.Body.LoginFuncResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.LoginFuncResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.LoginFuncAsync(WindowsFormsApp1.ServiceReference1.LoginFuncRequest request) {
            return base.Channel.LoginFuncAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.LoginFuncResponse> LoginFuncAsync(string email, string password) {
            WindowsFormsApp1.ServiceReference1.LoginFuncRequest inValue = new WindowsFormsApp1.ServiceReference1.LoginFuncRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.LoginFuncRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).LoginFuncAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.RegisterResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.Register(WindowsFormsApp1.ServiceReference1.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public void Register(string name, int age, int weight, string gender, string email, string password) {
            WindowsFormsApp1.ServiceReference1.RegisterRequest inValue = new WindowsFormsApp1.ServiceReference1.RegisterRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.RegisterRequestBody();
            inValue.Body.name = name;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            inValue.Body.gender = gender;
            inValue.Body.email = email;
            inValue.Body.password = password;
            WindowsFormsApp1.ServiceReference1.RegisterResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).Register(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.RegisterResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.RegisterAsync(WindowsFormsApp1.ServiceReference1.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.RegisterResponse> RegisterAsync(string name, int age, int weight, string gender, string email, string password) {
            WindowsFormsApp1.ServiceReference1.RegisterRequest inValue = new WindowsFormsApp1.ServiceReference1.RegisterRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.RegisterRequestBody();
            inValue.Body.name = name;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            inValue.Body.gender = gender;
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.ViewProfileResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.ViewProfile(WindowsFormsApp1.ServiceReference1.ViewProfileRequest request) {
            return base.Channel.ViewProfile(request);
        }
        
        public WindowsFormsApp1.ServiceReference1.UserClass ViewProfile(string email) {
            WindowsFormsApp1.ServiceReference1.ViewProfileRequest inValue = new WindowsFormsApp1.ServiceReference1.ViewProfileRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.ViewProfileRequestBody();
            inValue.Body.email = email;
            WindowsFormsApp1.ServiceReference1.ViewProfileResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).ViewProfile(inValue);
            return retVal.Body.ViewProfileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ViewProfileResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.ViewProfileAsync(WindowsFormsApp1.ServiceReference1.ViewProfileRequest request) {
            return base.Channel.ViewProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ViewProfileResponse> ViewProfileAsync(string email) {
            WindowsFormsApp1.ServiceReference1.ViewProfileRequest inValue = new WindowsFormsApp1.ServiceReference1.ViewProfileRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.ViewProfileRequestBody();
            inValue.Body.email = email;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).ViewProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.ViewDietPlanResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.ViewDietPlan(WindowsFormsApp1.ServiceReference1.ViewDietPlanRequest request) {
            return base.Channel.ViewDietPlan(request);
        }
        
        public WindowsFormsApp1.ServiceReference1.DietPlanClass ViewDietPlan(string type) {
            WindowsFormsApp1.ServiceReference1.ViewDietPlanRequest inValue = new WindowsFormsApp1.ServiceReference1.ViewDietPlanRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.ViewDietPlanRequestBody();
            inValue.Body.type = type;
            WindowsFormsApp1.ServiceReference1.ViewDietPlanResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).ViewDietPlan(inValue);
            return retVal.Body.ViewDietPlanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ViewDietPlanResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.ViewDietPlanAsync(WindowsFormsApp1.ServiceReference1.ViewDietPlanRequest request) {
            return base.Channel.ViewDietPlanAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ViewDietPlanResponse> ViewDietPlanAsync(string type) {
            WindowsFormsApp1.ServiceReference1.ViewDietPlanRequest inValue = new WindowsFormsApp1.ServiceReference1.ViewDietPlanRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.ViewDietPlanRequestBody();
            inValue.Body.type = type;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).ViewDietPlanAsync(inValue);
        }
    }
}
